config/routes.rb
Rails.application.routes.draw do
 
  resources :users
  resources :skills
  resources :categories
  resources :users
  resources :sessions

  get '/github' => 'users#github'
  get '/uers/repos' => 'users#repos', as: :repos
  get "/auth/:provider/callback" => "session#create"

  root 'users#index'
 
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
 
 

  private
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def current_user=(user)
  current_user = user
  end
  def current_user=(user)
  sign_in(user)
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/github_controller.rb
class GithubsController < ApplicationController
  def github
    # Find the access token
    res = HTTParty.post('https://github.com/login/oauth/access_token',
      {body:{client_id: ENV["GH_CLIENT_ID"],
       client_secret: ENV["GH_CLIENT_SECRET"],
       code: params[:code]},
       headers: {"Accept" => "application/json"}})
    puts "Github"
    puts res.parsed_response.inspect
    redirect_to repos_path(acc_token: res.parsed_response["access_token"])
  end

  def repos

    @user = User.new
    # Show info about this user
    headers = {"User-Agent" => "SKILLZ",
      "Authorization" => "token #{params[:acc_token]}"}
    url = "https://api.github.com/user" # ?access_token=#{URI::escape(params[:acc_token])}
    @user_info = HTTParty.get(url, headers: headers)
    # Based on the URLs returned, let's find out about the repos
    @repos = HTTParty.get(@user_info["repos_url"], headers: headers)
  end

   def destroy
    reset_session
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def show
  end

  def new
    @user = User.new
    @is_login = true
  end

    def create
    u = User.where(email: params[:user][:email]).first
    #First make sure we actually found a user
    #Then, see if their password matches
    if u && u.authenticate(params[:user][:password])
      #Throw a cookie at the user that holds the logged in user ID
      session[:user_id] = u.id.to_s
      redirect_to ballots_path
    else
      redirect_to :back
    end
  end

  def edit
  end

  def update
  end

  def destroy
    #Kill all of our cookies
    reset_session
    redirect_to users_path
  end

  def github
    # Find the access token
    res = HTTParty.post('https://github.com/login/oauth/access_token',
      {body:{client_id: ENV["GH_CLIENT_ID"],
       client_secret: ENV["GH_CLIENT_SECRET"],
       code: params[:code]},
       headers: {"Accept" => "application/json"}})
    puts "Github"
    puts res.parsed_response.inspect
    redirect_to repos_path(acc_token: res.parsed_response["access_token"])
  end
  def repos
    # Show info about this user
    headers = {"User-Agent" => "SKILLZ",
      "Authorization" => "token #{params[:acc_token]}"}
    url = "https://api.github.com/user" # ?access_token=#{URI::escape(params[:acc_token])}
    @user = HTTParty.get(url, headers: headers)
    # Based on the URLs returned, let's find out about the repos
    @repos = HTTarty.get(@user["repos_url"], headers: headers)
  end
  def destroy
    reset_session
    redirect_to root_url, :notice => "Signed out!"
  end
 
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(params.require(:user).permit(:name, :github_name, :avatar_url, :followers, :following, :public_repos))
      if user.save
        redirect_to new_session_path
      end
    end

  def edit
  end

  def update
  end

  def destroy
  end

  def github

    # Find the access token
    res = HTTParty.post('https://github.com/login/oauth/access_token',
      {body:{client_id: ENV["GH_CLIENT_ID"],
       client_secret: ENV["GH_CLIENT_SECRET"],
       code: params[:code]},
       headers: {"Accept" => "application/json"}})
    puts "Github"
    puts res.parsed_response.inspect
    redirect_to repos_path(acc_token: res.parsed_response["access_token"])
  end
  def repos
    @user_new = User.new
    # Show info about this user
    headers = {"User-Agent" => "SKILLZ",
      "Authorization" => "token #{params[:acc_token]}"}
    url = "https://api.github.com/user" # ?access_token=#{URI::escape(params[:acc_token])}
    @user = HTTParty.get(url, headers: headers)
    # Based on the URLs returned, let's find out about the repos
    @repos = HTTParty.get(@user["repos_url"], headers: headers)
  end
  def destroy
    reset_session
    redirect_to root_url, :notice => "Signed out!"
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/github/repos.html.erb
<h1>Welcome <%= @user_info["login"] %></h1>
<table>
  <tr><td class="topColumn"><%= image_tag @user_info["avatar_url"] %></td>
  <td>You social butterfly -- you've got <%= @user_info["followers"] %> people following you, and in return are following <%= @user_info["following"] %>.  Here's your <%= @user_info["public_repos"] %> repositories:<br />

    <% @repos.each do |r| %>
      <h3><%= link_to r["name"], r["html_url"] %></h3>
      <%= r["description"] %><br />
      <b>Clone this <%= r["language"] %> app:</b>
      <pre>git clone <%= r["clone_url"] %></pre>
    <% end %>

  </td></tr>
  isuhfdoshjfkslj
<%= link_to "Logout", @user, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skillz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/skills/create.html.erb
<h1>Skills#create</h1>
<p>Find me in app/views/skills/create.html.erb</p>

app/views/skills/destroy.html.erb
<h1>Skills#destroy</h1>
<p>Find me in app/views/skills/destroy.html.erb</p>

app/views/skills/edit.html.erb
<h1>Skills#edit</h1>
<p>Find me in app/views/skills/edit.html.erb</p>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>

app/views/skills/new.html.erb
<h1>Skills#new</h1>
<p>Find me in app/views/skills/new.html.erb</p>
<% if current_user %>
current_user moo moo
<% end %>

app/views/skills/show.html.erb
<h1>Skills#show</h1>
<p>Find me in app/views/skills/show.html.erb</p>

app/views/skills/update.html.erb
<h1>Skills#update</h1>
<p>Find me in app/views/skills/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<a href="https://github.com/login/oauth/authorize?scope=user:email&client_id=<%= ENV["GH_CLIENT_ID"] %>">Log into Github</a>

what up

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<% if current_user %>
 Welcome <%= current_user.name %>
  <% else %>
  <%= link_to "Sign in with Github", "/auth/github" %>
<% end %>

app/views/users/repos.html.erb
<h1>Welcome <%= @user["login"] %></h1>
<table>
  <tr><td class="topColumn"><%= image_tag @user["avatar_url"] %></td>
  <td>You social butterfly -- you've got <%= @user["followers"] %> people following you, and in return are following <%= @user["following"] %>.  Here's your <%= @user["public_repos"] %> repositories:<br />

    <% @repos.each do |r| %>
      <h3><%= link_to r["name"], r["html_url"] %></h3>
      <%= r["description"] %><br />
      <b>Clone this <%= r["language"] %> app:</b>
      <pre>git clone <%= r["clone_url"] %></pre>
    <% end %>

  </td></tr>
<%= link_to "new skill", new_skill_path %>
<%= link_to "Log out", new_session_path, method: :delete %>


        
        <%= form_for @user_new do |f| %>
            <%= f.text_field :name, placeholder: "What's your first name?" %>
            <%= f.hidden_field :github_name, :value => @user["login"]  %>
            <%= f.hidden_field :avatar_url, :value => @user["avatar_url"]  %>
            <%= f.hidden_field :followers, :value => @user["followers"]  %>
            <%= f.hidden_field :following, :value => @user["following"]  %>
         
            <%= f.submit  "Confirm" %>
         
          <% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>